# Generated by Django 3.0.4 on 2020-03-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
